# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "heroku-rglpk"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Gutteridge", "William Taysom"]
  s.date = "2012-11-22"
  s.description = "Rglpk is a package providing a Ruby wrapper to the [GNU GLPK](http://www.gnu.org/software/glpk/) library.  The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems.\n\nRglpk (pronounced as \"wriggle-pick\") is currently in alpha status and the API should be considered subject to change.  Rglpk uses [Swig](http://www.swig.org/) to initially wrap the C GLPK library (using a Swig wrapper originally developed by Nigel Galloway) and then a pure Ruby library to wrap the Swig code in a more friendly OO-style.\n\nSee [github](http://github.com/wtaysom/rglpk) for installation instructions.  All bug reports, feature requests and patches are welcome.  Enjoy!"
  s.email = ["alexg@kuicr.kyoto-u.ac.jp", "wtaysom@gmail.com"]
  s.extensions = ["ext/extconf.rb", "ext/extconf.rb"]
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    "ChangeLog.md",
    "License.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ext/extconf.rb",
    "ext/glpk-4.44.tar.gz",
    "ext/glpk_install/bin/glpsol",
    "ext/glpk_install/include/glpk.h",
    "ext/glpk_install/lib/libglpk.a",
    "ext/glpk_install/lib/libglpk.la",
    "ext/glpk_install/lib/libglpk.so",
    "ext/glpk_install/lib/libglpk.so.0",
    "ext/glpk_install/lib/libglpk.so.0.29.0",
    "ext/glpk_wrapper.c",
    "heroku-rglpk.gemspec",
    "lib/rglpk.rb",
    "swig/Makefile.in",
    "swig/configure.in",
    "swig/glpk.i",
    "test/helper.rb",
    "test/test_all.rb",
    "test/test_basic.rb",
    "test/test_brief_example.rb",
    "test/test_problem_kind.rb"
  ]
  s.require_paths = ["lib", "ext", "ext/glpk_install/lib", "ext", "ext/glpk_install/lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Rglpk is a package providing a Ruby wrapper to the [GNU GLPK](http://www.gnu.org/software/glpk/) library.  The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

